<?php
$this->headScript()->appendScript('$(function(){$("ul li.admin-area").addClass("active");})');

$headTitle = 'Edit user';
$this->headTitle($headTitle);
?>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Are You sure?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger" id="delete-user">Yes</button>
            </div>
        </div>
    </div>
</div>
<!-- Hidden form for delete user or admin -->
<form action="<?= $this->url('admin/users', ['action' => 'delete', 'id' => (int)$this->user->getId(), 'page' => $this->page]) ?>"
      method="post"
      class="modal-form"
>
    <button type="button">Yes</button>
</form>
<div class="well">
    <div class="row">
        <div class="col-sm-10">
            <form action="<?= $this->url('admin/users', ['action' => 'edit', 'id' => (int)$this->user->getId(), 'page' => $this->page]) ?>"
                  method="post"
                  class="form-horizontal"
            >
                <fieldset>
                    <legend>Form for editing <?= $this->user->getRole()?></legend><br>
                    <div class="form-group">
                        <label class="control-label col-sm-3">User name</label>
                        <div class="col-sm-9">
                            <input type="text" name="name" value="<?= $this->user->getName() ?>" disabled class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Email address</label>
                        <div class="col-sm-9">
                            <input type="text" name="email" value="<?= $this->user->getEmail() ?>" disabled class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3" for="role">Role</label>
                        <div class="col-sm-9">
                            <select name="role" class="form-control" id="role">
                                <option><?= $this->user->getRole() ?></option>
                                <option><?= ($this->user->getRole() == 'admin') ? 'user' : 'admin'; ?></option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12 col-sm-offset-3">
                            <input type="submit" name="submit" value="Submit" class="btn btn-default">
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
<hr>
<button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#myModal">
    Delete <?= $this->user->getRole()?>
</button>
